# Generated by Django 2.2.1 on 2019-06-02 13:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_auto_20190602_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bookman',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
