# Generated by Django 2.2.1 on 2019-06-02 13:37

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_auto_20190602_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='poster',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
