# Generated by Django 2.2.1 on 2019-06-13 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_bookrequest_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='poster',
        ),
        migrations.AlterField(
            model_name='booker',
            name='bookman',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='bookman',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
