# Generated by Django 2.2.1 on 2019-06-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_auto_20190613_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
